// Core types
export type {
  Image,
  User,
  Artist,
  Album,
  Track,
  Playlist,
  SimplifiedPlaylist,
  SearchOptions,
  SearchResult,
  PaginatedResult,
  CurrentUser,
  Device,
  PlaybackState,
  PlayOptions,
  SpotifyUserAuthConfig,
  RecommendationSeeds,
  RecommendationOptions,
  RecentlyPlayedItem,
  TimeRange,
  TopItemsOptions,
  CreatePlaylistOptions,
  PlaylistDetails,
  QueueState,
  RepeatMode,
  SpotifyConfig,
  SpotifyAdapter,
  SpotifyUserAdapter,
} from "./types";

// Error classes
export {
  AuthenticationError,
  NotFoundError,
  RateLimitError,
  NetworkError,
  SpotifyApiError,
  ValidationError,
  PremiumRequiredError,
  NoActiveDeviceError,
} from "./errors";
